name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo hi
    - name: Run a multi-line script
      run: |
        echo meow
        
        mkdir /tmp/logs
        echo meow > /tmp/logs/cat.log
        df -h
        exit 1
